# Python(파이썬) : 프로그래밍 언어 중 하나. 간단한 프로그래밍 언어를 지향

<hr>

## 파이썬의 특징
- 간단한 문법구조 : 빠르고 쉽게 익힐 수 있음
- 자료형 명시의 불필요 : 자료형에 집중하지 않고 편리하게 사용 가능. 가변적이므로 형변환 불필요
- 인터프리터 언어 : 컴파일 과정 없이 한줄마다 프로그램을 실행, 오류가 있어도 오류 전까지 정상실행
- 직관적인 작성 추구 : 같은 내용도 매우 다양한 방법으로 작성이 가능

## 파이썬 개발환경
- IDLE
- Jupyter Notebook (Anaconda) [권장]
- Google Colab [권장]
- PyCharm
- etc...

### 변수의 선언 : 변수명 = 값
위와 같은 형태로 선언한다. 즉 처음 사용하는 변수에 대한 값의 대입은 변수의 선언을 의미한다.

In [ ]:
a = 2
b = 3.14
c = True
d = "hello"
e = [1,2,3]

## 자료형

### Integer : 정수형 자료를 저장. (크기제한 없음)
- ex) 5, -1, 0 ...
- 이진수(0b\~), 팔진수(0o\~), 십육진수(0x\~) 등으로 각종 진수로도 표현 가능
- 정수끼리 +(덧셈), -(뺄셈), *(곱셈), //(나눗셈의 몫), %(나눗셈의 나머지), **(지수연산)을 할 경우 결과는 정수
- 연산 과정에 부동소수가 있다면 결과는 부동소수
- /(나눗셈)은 무조건 부동소숫값 반환

In [ ]:
print(type(5), type(-1), type(0))

<class 'int'> <class 'int'> <class 'int'>


In [ ]:
5 + 2

7

In [ ]:
5 - 2

3

In [ ]:
5 * 2

10

In [ ]:
5 // 2

2

In [ ]:
5 % 2

1

In [ ]:
5 - 2 + 0.1

3.1

In [ ]:
5 / 2

2.5

### Floating-Point : 실수형(부동소수형) 자료를 저장. (크기제한 없음)
- ex) 1.0, -5.3, 3.1415, 3e5 ...
- 위의 예시처럼 e(지수표기법) 사용가능. e는 *10<sup>(뒤의 수)</sup>로 해석
- 정수와의 연산에서는 정수가 실수로 자동으로 형변환됨
- 연산 결과는 항상 실수

In [ ]:
print(type(1.0), type(-5.3), type(3.1415), type(3e5))

<class 'float'> <class 'float'> <class 'float'> <class 'float'>


In [ ]:
5 + 3.14

8.14

### Bool : 논리(참거짓) 자료를 저장. True, False만 저장가능
- ex) True 또는 False
- +, - 등 연산 시 True==1, False==0 으로 간주
- and, or, not 사용
- ==(같다), <=(작거나 같다), >=(크거나 같다), >(크다), <(작다), !=(다르다) 등의 연산결과는 Bool(True/False)로 표현
- 3 < 5 < 7 처럼 논리연산자를 연결 가능. 즉, 논리연산자가 연결되어 있으면 and로 묶인 것으로 봄

In [ ]:
print(type(True), type(False))

<class 'bool'> <class 'bool'>


In [ ]:
True and True, True and False, False and True, False and False

(True, False, False, False)

In [ ]:
True or True, True or False, False or True, False or False

(True, True, True, False)

In [ ]:
not True, not False

(False, True)

In [ ]:
5 == 5, 5 <= 2, 5 >= 2, 5 < 2, 5 > 2, 5 != 2

(True, False, True, False, True, True)

In [ ]:
5 > 2 and 5 == 2, 5 > 2 or 5 == 2

(False, True)

In [ ]:
3 < 5 < 7

True

### String : 문자열 자료를 저장

- "문자열", '문자열' 두 방법 모두 사용 가능
- '''문자열''', """문자열""" 또한 사용가능 / 주석용도로도 사용
- '문자열' + "문자열" 처럼 덧셈으로 연결하면 문자열 결합 가능
- '문자열' + 1 처럼 문자열끼리의 덧셈이 아니라면 불가능 ('문자열' + str(1) 처럼 형변환 필요)
- '문자열' * 4 처럼 숫자를 통해 문자열 여러개를 붙이기 가능
- 배열처럼 접근가능 : "문자열"[1], "문자열"[-1], "문자열"[0:2] 등
- 변수명.split(값)을 통해 문자열 나누기 가능 : "a b".split() == ['a', 'b']

In [ ]:
print(type("True"), type('abc'), type("""배고파"""), type('''파이썬'''))

<class 'str'> <class 'str'> <class 'str'> <class 'str'>


In [ ]:
'''코드 내부에서 주석용으로 사용가능'''

'코드 내부에서 주석용으로 사용가능'

In [ ]:
"강아지" + "vs" + "고양이"

'강아지vs고양이'

In [ ]:
"고양" + 2

TypeError: can only concatenate str (not "int") to str

In [ ]:
"고양" + str(2)

'고양2'

In [ ]:
"밥줘" * 4

'밥줘밥줘밥줘밥줘'

In [ ]:
"문자열은 배열처럼 접근이 가능하데요"[0]

'문'

In [ ]:
"문자열은 배열처럼 접근이 가능하데요"[-1]

'요'

In [ ]:
"문자열은 배열처럼 접근이 가능하데요"[0:3]

'문자열'

In [ ]:
"문자열을 나눌수 있데요".split()

['문자열을', '나눌수', '있데요']

In [ ]:
"2002-03-20".split('-')

['2002', '03', '20']

### List : 리스트
- [1, 2, 3]처럼 표기. [1, "2", [3, 2, "1"]]처럼 내부 자료형이 달라도 됨
- a = [1, 2, 3] / a[0] == 1 / a[-1] == 3 / a[2] == 3 / a[0:2] == [1, 2]
- 빈 리스트 선언 가능 : arr = []
- arr.append(값) : 리스트 맨 뒤에 항목 추가
- arr.remove(값) : 해당 값 제거
- arr.insert(위치, 값) : 해당 위치에 값 삽입
- arr.index(값) : 해당 값 위치 구하기
- arr.count(값) : 해당 값 
- arr.sort() : arr 리스트 정렬
- \+ : 리스트 합치기 : 문자열과 마찬가지로 반복해서 이어붙임

In [ ]:
print(type([1, 2, 3]))

<class 'list'>


In [ ]:
[1, "2", [3, 2, "1"]]

[1, '2', [3, 2, '1']]

In [ ]:
a = [1, 2, 3]

In [ ]:
a[0]

1

In [ ]:
a[-1]

3

In [ ]:
a[2]

3

In [ ]:
a[0:2]

[1, 2]

In [ ]:
a.append(2)
a

[1, 2, 3, 2]

In [ ]:
a.remove(2)
a

[1, 3, 2]

In [ ]:
a.insert(1,2)
a

In [ ]:
a.index(2)

1

In [ ]:
a.count(2)

2

In [ ]:
a.sort()
a

[1, 2, 2, 3]

### Tuple : 리스트와 비슷하나 상수처럼 취급
- (1, 2, 3)처럼 표기 / 괄호가 없어도 Tuple로 취급
- 값의 추가/변경/삭제 가 불가능
- index, count 사용가능

In [ ]:
print(type((1, 2, 3)))

<class 'tuple'>


In [ ]:
1, 2, 3

(1, 2, 3)

In [ ]:
b = (1, 2, 3)

In [ ]:
b.append(2)

AttributeError: 'tuple' object has no attribute 'append'

In [ ]:
b.index(3)

2

In [ ]:
b.count(1)

1

### Dictionary : 사전형. 흔히 JSON 형태로 많이 알려짐
- {}로 중괄호로 묶음
- 내부 형식은 key : value
- 값 얻기 : a = {key : value}일 때, a[key]
- 값 추가하기 : a[newKey] = newValue 와 같이 없는 키를 넣으면 새로 생성

In [ ]:
print(type({}))

<class 'dict'>


In [ ]:
c = {"day" : '0513', 'name':'JW'}

In [ ]:
c['day']

'0513'

In [ ]:
c['age']=21
c

{'day': '0513', 'name': 'JW', 'age': 21}

### 파이썬의 기본적인 내장 함수

#### 출력 함수
- print(value, ... , sep = ' ', end  = '\n')
    - sep : value들 사이에 들어갈 값
    - end : print 출력 끝에 들어갈 값

In [ ]:
print(1)

1


In [ ]:
a = "hello"
b = "python"
print(a,b)
print(a,b,sep='-')
print(a,b,end='. ')
print("다음줄에 출력되지 않음", '!', sep='')

hello python
hello-python
hello python. 다음줄에 출력되지 않음!


#### 형변환
 - 변환하고싶은_자료형(변환하고싶은 값) 형태로 사용

In [ ]:
a = 1
type(a)

int

In [ ]:
a = float(a)
print(type(a), a)

<class 'float'> 1.0


#### 입력 함수 : 줄바꿈이 나올 때 까지 입력받음.
- input()
    - return type : srting
    
- input().split(" ")
    - split의 값을 기준으로 srting를 나눔
    - return type : list

In [ ]:
input()

123


'123'

In [ ]:
input().split()

rkskek fkakqk


['rkskek', 'fkakqk']

In [ ]:
d = input()
type(d)

123


str

In [ ]:
d = int(d)
type(d)

int

#### range() 함수
- range(start, stop, step)
    - return type : range
    - list로 형변환 필요
        - [start, start + step, ... , stop - 1]
            - start default : 0
            - step default : 1
    - 인자가 하나이면 stop가 인자값
    - 인자가 두개이면 start와 stop의 값

In [ ]:
range(10)

range(0, 10)

In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
list(range(5, 10))

[5, 6, 7, 8, 9]

In [ ]:
list(range(5, 10, 2))

[5, 7, 9]

#### len() 함수
- 리스트, 튜플 등의 길이 측정

In [ ]:
a = list(range(10))
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
len(a)

10

In [ ]:
b = (1, 2, 3)
len(b)

3

### 파이썬 필수 문법

#### if, elif, else 조건문
```python
if 조건1:
    실행내용
elif 조건2:
    실행내용
else:
    실행내용
```

In [ ]:
score = 88

if score > 80:
    print("pass")
    
else:
    print('fail')

pass


In [ ]:
if score > 90:
    print("A")
elif score > 80:
    print("B")
elif score > 70:
    print("C")
elif score > 60:
    print("D")
else:
    print("F")

B


#### for 반복문
```python
for 변수명 in range():
    실행내용
```
이때 range() 부분에는 list, string 등이 올 수도 있다.

In [ ]:
for i in range(5):
    print(i)

0
1
2
3
4


In [ ]:
for i in [1, 2, 3]:
    print(i)

1
2
3


In [ ]:
for i in "인공지능 어려움":
    print(i)

인
공
지
능
 
어
려
움


#### 함수
```python
def 함수명(인자1, 인자2, ... ):
    내용 ~
    
    return 값
```
return이나 내용은 생략 가능한 경우가 존재

In [ ]:
def 인사():
    print('안녕하세요')

In [ ]:
인사()

안녕하세요


In [ ]:
def add_func(x,y):
    return x+y

In [ ]:
add_func(1,2)

3

In [ ]:
def cat_meal_time(time):
    if time%6==0:
        print(time, '시 입니다.\n','고양이 밥줄 시간입니다', sep='')

In [ ]:
for i in range(1,13):
    cat_meal_time(i)

6시 입니다.
고양이 밥줄 시간입니다
12시 입니다.
고양이 밥줄 시간입니다


## 파이썬의 라이브러리

#### 모듈  
각종 기능을 미리 구현해두어 쉽게 사용할 수 있게 한 것.  
함수 등을 하나의 파일로 뭉쳐둠

#### 라이브러리  
모듈을 그룹화한 것

1. import 모듈이름
2. import 모듈이름 as 약칭
3. from 모듈이름 import 모듈에서 가져올 함수들
4. from 모듈이름 import *
    - 모듈의 모든 함수를 가져옴으로써 모듈 이름 작성의 번거로움 생략
    
#### 가져온 함수 등의 사용

1. 모듈이름.함수명

In [ ]:
import itertools
itertools.permutations([1,2,3])

2. 약칭.함수명

In [ ]:
import itertools as tool
tool.permutations([1,2,3])

3. from 모듈이름 import 특정 함수

In [ ]:
from numpy import random
a = random.rand(5)
print(a)

[0.22790251 0.47440175 0.46065915 0.83873327 0.76252878]


4. from 모듈이름 import *

In [ ]:
from numpy import*
a=array([1,2,3])
print(a)

[1 2 3]


## Numpy
수학 및 과학의 계산을 담당하는 모듈

```python
import numpy as np
```

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a[:1]

array([[1, 2, 3]])

In [ ]:
a[0][:2]

array([1, 2])

In [ ]:
a[:,2]

array([3, 6])

In [ ]:
a[:,[1,2]]

array([[2, 3],
       [5, 6]])

In [ ]:
a[a>2]

array([3, 4, 5, 6])

In [ ]:
b = np.array([[1,2],[3,4],[5,6]])

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

### 행렬 곱

(n, m) @ (m, k) = (n, k)

In [ ]:
a@b

array([[22, 28],
       [49, 64]])

### 별곱
같은 shape일때 연산됨

같은위치끼리 곱하여 만들어짐

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])

In [ ]:
print(a.shape, b.shape)

(2, 3) (2, 3)


In [ ]:
a*b

array([[ 7, 16, 27],
       [40, 55, 72]])